### ISSUE TITLE
群满了，有新的群么？

### ISSUE THREAD

**Issue by Arnold-Zhang** [lobtao/phpdesktop#3]
请问有新的群不？谢谢呀

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lobtao** [comment]
群可以正常加入了


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lobtao** [comment]
https://github.com/flutterchina/flukit


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by fashionwill** [comment]
群已经加满了
